# Generated by Django 3.0.5 on 2023-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('marks', models.FloatField()),
                ('section', models.CharField(max_length=20)),
            ],
        ),
    ]
