# Generated by Django 3.0.5 on 2023-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.CharField(default='https://www.bing.com/images/search?view=detailV2&ccid=L6o7cqG7&id=67660AC9C2EA2DFD9EB57F58A7BCF0EC1C490653&thid=OIP.L6o7cqG7wtxCvKU9xD5bJQHaLJ&mediaurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.2faa3b72a1bbc2dc42bca53dc43e5b25%3frik%3dUwZJHOzwvKdYfw%26riu%3dhttp%253a%252f%252fwww.promotionalbooktours.com%252fwp-content%252fuploads%252f2014%252f04%252fAbiding-Flame_ebooklg.jpg%26ehk%3diRumIjSrYCvxNYzU4lHJnqi1SPUba9d3VlzkCh8ka%252bQ%253d%26risl%3d1%26pid%3dImgRaw%26r%3d0&exph=2408&expw=1600&q=book&simid=607999487932383049&FORM=IRPRST&ck=0DC558BFD4C7C6F165CF49A4779D8DC0&selectedIndex=8', max_length=2000),
        ),
    ]
