# Generated by Django 3.0.5 on 2023-06-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0004_auto_20230602_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
