# Generated by Django 3.0.5 on 2023-06-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0005_remove_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pic',
            new_name='pics',
        ),
    ]
