# Generated by Django 3.0.5 on 2023-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0006_auto_20230602_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pics',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kqT6XFsG2BTW22Y4st2-KAHaHa?pid=ImgDet&rs=1', max_length=1000),
        ),
    ]
